name: Deploy all

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude=".git .github .env"
        path: .
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.VPS_HOST }}
        remote_user: ${{ secrets.VPS_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Restart Docker on VPS
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
        cd ${{ secrets.DEPLOY_PATH }}
        docker compose --file docker-compose.yml up -d --build 
        EOF